<a href="https://colab.research.google.com/github/amaguilerac/SBDM_stackoverflow-_survey_results/blob/master/Trabajo1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install sodapy

Collecting sodapy
  Downloading https://files.pythonhosted.org/packages/9e/74/95fb7d45bbe7f1de43caac45d7dd4807ef1e15881564a00eef489a3bb5c6/sodapy-2.1.0-py2.py3-none-any.whl
Requirement already satisfied: requests>=2.20.0 in /usr/local/lib/python3.6/dist-packages (from sodapy) (2.23.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/dist-packages (from requests>=2.20.0->sodapy) (2020.6.20)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.6/dist-packages (from requests>=2.20.0->sodapy) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.6/dist-packages (from requests>=2.20.0->sodapy) (2.10)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.6/dist-packages (from requests>=2.20.0->sodapy) (1.24.3)
Installing collected packages: sodapy
Successfully installed sodapy-2.1.0

In [ ]:
#Cargar datos
import pandas as pd
from sodapy import Socrata

client = Socrata("www.datos.gov.co", None)

results = client.get("gt2j-8ykr",limit= 200000000)

results_df = pd.DataFrame.from_records(results)
results_df

WARNING:root:Requests made without an app_token will be subject to strict throttling limits.

       id_de_caso    fecha_de_notificaci_n  ... nombre_grupo_etnico fecha_de_muerte
0               1  2020-03-02T00:00:00.000  ...                 NaN             NaN
1               2  2020-03-06T00:00:00.000  ...                 NaN             NaN
2               3  2020-03-07T00:00:00.000  ...                 NaN             NaN
3               4  2020-03-09T00:00:00.000  ...                 NaN             NaN
4               5  2020-03-09T00:00:00.000  ...                 NaN             NaN
...           ...                      ...  ...                 ...             ...
456684     456725  2020-07-20T00:00:00.000  ...                 NaN             NaN
456685     456726  2020-07-26T00:00:00.000  ...                 NaN             NaN
456686     456727  2020-07-26T00:00:00.000  ...                 NaN             NaN
456687     456728  2020-07-26T00:00:00.000  ...                 NaN             NaN
456688     456729  2020-07-26T00:00:00.000  ...                 NaN             NaN

[456689 rows x 21 columns]

In [ ]:
#Elegir columnas

covid = results_df[['id_de_caso','fecha_de_notificaci_n','c_digo_divipola','ciudad_de_ubicaci_n','departamento','atenci_n','edad','sexo','tipo','estado','pa_s_de_procedencia','fis','fecha_diagnostico','fecha_recuperado','fecha_reporte_web','tipo_recuperaci_n','codigo_departamento','codigo_pais','pertenencia_etnica','nombre_grupo_etnico','fecha_de_muerte']].copy()
covid

       id_de_caso    fecha_de_notificaci_n  ... nombre_grupo_etnico fecha_de_muerte
0               1  2020-03-02T00:00:00.000  ...                 NaN             NaN
1               2  2020-03-06T00:00:00.000  ...                 NaN             NaN
2               3  2020-03-07T00:00:00.000  ...                 NaN             NaN
3               4  2020-03-09T00:00:00.000  ...                 NaN             NaN
4               5  2020-03-09T00:00:00.000  ...                 NaN             NaN
...           ...                      ...  ...                 ...             ...
456684     456725  2020-07-20T00:00:00.000  ...                 NaN             NaN
456685     456726  2020-07-26T00:00:00.000  ...                 NaN             NaN
456686     456727  2020-07-26T00:00:00.000  ...                 NaN             NaN
456687     456728  2020-07-26T00:00:00.000  ...                 NaN             NaN
456688     456729  2020-07-26T00:00:00.000  ...                 NaN             NaN

[456689 rows x 21 columns]

In [ ]:
# Cambio nombres
covid = covid.rename(columns={'id_de_caso':'ID','fecha_de_notificaci_n':'fecha_notificacion','c_digo_divipola':'cod D','ciudad_de_ubicaci_n':'ciudad_ubicacion', 'atenci_n': 'atencion', 'pa_s_de_procedencia': 'pais_procedencia','fecha_diagnostico': 'fecha_diagnostico','fecha_reporte_web':'fecha_reporte','tipo_recuperaci_n':'tipo_recuperacion','nombre_grupo_etnico':'grupo_etnico','fecha_de_muerte':'fecha_muerte'})
covid

            ID       fecha_notificacion  ... grupo_etnico fecha_muerte
0            1  2020-03-02T00:00:00.000  ...          NaN          NaN
1            2  2020-03-06T00:00:00.000  ...          NaN          NaN
2            3  2020-03-07T00:00:00.000  ...          NaN          NaN
3            4  2020-03-09T00:00:00.000  ...          NaN          NaN
4            5  2020-03-09T00:00:00.000  ...          NaN          NaN
...        ...                      ...  ...          ...          ...
456684  456725  2020-07-20T00:00:00.000  ...          NaN          NaN
456685  456726  2020-07-26T00:00:00.000  ...          NaN          NaN
456686  456727  2020-07-26T00:00:00.000  ...          NaN          NaN
456687  456728  2020-07-26T00:00:00.000  ...          NaN          NaN
456688  456729  2020-07-26T00:00:00.000  ...          NaN          NaN

[456689 rows x 21 columns]

In [ ]:
#Cambio formato fecha
covid["fecha_notificacion"]= covid["fecha_notificacion"].str.split("T",2).str[0]
covid["fis"]= covid["fis"].str.split("T",2).str[0]
covid["fecha_diagnostico"]= covid["fecha_diagnostico"].str.split("T",2).str[0]
covid["fecha_recuperado"]= covid["fecha_recuperado"].str.split("T",2).str[0]
covid["fecha_reporte"]= covid["fecha_reporte"].str.split("T",2).str[0]
covid

            ID fecha_notificacion  ... grupo_etnico fecha_muerte
0            1         2020-03-02  ...          NaN          NaN
1            2         2020-03-06  ...          NaN          NaN
2            3         2020-03-07  ...          NaN          NaN
3            4         2020-03-09  ...          NaN          NaN
4            5         2020-03-09  ...          NaN          NaN
...        ...                ...  ...          ...          ...
456684  456725         2020-07-20  ...          NaN          NaN
456685  456726         2020-07-26  ...          NaN          NaN
456686  456727         2020-07-26  ...          NaN          NaN
456687  456728         2020-07-26  ...          NaN          NaN
456688  456729         2020-07-26  ...          NaN          NaN

[456689 rows x 21 columns]

In [ ]:
covid.describe()

            ID fecha_notificacion  ... grupo_etnico             fecha_muerte
count   456689             456689  ...         6478                    15615
unique  456689                164  ...           83                      148
top     154678         2020-07-27  ...         ZENÚ  2020-07-30T00:00:00.000
freq         1              11213  ...         1449                      353

[4 rows x 21 columns]

In [ ]:
covid.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 456689 entries, 0 to 456688
Data columns (total 21 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   ID                   456689 non-null  object
 1   fecha_notificacion   456689 non-null  object
 2   cod D                456689 non-null  object
 3   ciudad_ubicacion     456689 non-null  object
 4   departamento         456689 non-null  object
 5   atencion             456689 non-null  object
 6   edad                 456689 non-null  object
 7   sexo                 456689 non-null  object
 8   tipo                 456689 non-null  object
 9   estado               456689 non-null  object
 10  pais_procedencia     964 non-null     object
 11  fis                  456689 non-null  object
 12  fecha_diagnostico    452854 non-null  object
 13  fecha_recuperado     274433 non-null  object
 14  fecha_reporte        456689 non-null  object
 15  tipo_recuperacion    274421 non-null  object
 16  codigo_departamento  456689 non-null  object
 17  codigo_pais          964 non-null     object
 18  pertenencia_etnica   289343 non-null  object
 19  grupo_etnico         6478 non-null    object
 20  fecha_muerte         15615 non-null   object
dtypes: object(21)
memory usage: 73.2+ MB

In [ ]:
#Tabla de frecuencias
Frecuencias=pd.DataFrame(covid.groupby('ciudad_ubicacion')['ciudad_ubicacion'].count())
Frecuencias.columns=['conteo']
Frecuencias=Frecuencias.reset_index()
Frecuencias['prob']=Frecuencias['conteo']/Frecuencias['conteo'].sum()
Frecuencias

    ciudad_ubicacion  conteo      prob
0          Abejorral      11  0.000024
1           Abriaquí      18  0.000039
2            Acacías     158  0.000346
3             Acandí      27  0.000059
4            Acevedo       4  0.000009
..               ...     ...       ...
904    Zona Bananera     189  0.000414
905           Ábrego      44  0.000096
906           Íquira       7  0.000015
907           Úmbita       5  0.000011
908            Útica       1  0.000002

[909 rows x 3 columns]

In [ ]:
import seaborn as sb

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

In [ ]:
#Selección de ciudades
covid2 = covid[covid.ciudad_ubicacion.isin(['Medellín','Cali', 'Bogotá D.C.','Cartagena de Indias','Barranquilla'])]
covid2

            ID fecha_notificacion  ... grupo_etnico fecha_muerte
0            1         2020-03-02  ...          NaN          NaN
2            3         2020-03-07  ...          NaN          NaN
3            4         2020-03-09  ...          NaN          NaN
4            5         2020-03-09  ...          NaN          NaN
6            7         2020-03-08  ...          NaN          NaN
...        ...                ...  ...          ...          ...
456604  456645         2020-05-29  ...          NaN          NaN
456607  456648         2020-06-04  ...          NaN          NaN
456609  456650         2020-05-22  ...          NaN          NaN
456611  456652         2020-05-05  ...          NaN          NaN
456624  456665         2020-07-10  ...          NaN          NaN

[274493 rows x 21 columns]

In [ ]:
#Tabla de frecuencias
Frecuencias=pd.DataFrame(covid2.groupby('ciudad_ubicacion')['ciudad_ubicacion'].count())
Frecuencias.columns=['conteo']
Frecuencias=Frecuencias.reset_index()
Frecuencias['prob']=Frecuencias['conteo']/Frecuencias['conteo'].sum()
Frecuencias

      ciudad_ubicacion  conteo      prob
0         Barranquilla   34140  0.124375
1          Bogotá D.C.  158674  0.578062
2                 Cali   29117  0.106076
3  Cartagena de Indias   18049  0.065754
4             Medellín   34513  0.125734

In [ ]:
plt.hist(covid2['precio'],bins=60)
plt.show()